name: DevOps CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend
        run: cd backend && npm install

      - name: Lint backend
        run: cd backend && npm run lint

      - name: Test backend
        run: cd backend && npm test

      - name: Install frontend
        run: cd frontend && npm install

      - name: Lint frontend
        run: cd frontend && npm run lint

      - name: Build frontend
        run: cd frontend && npm run build

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Scan dependances npm audit
        run: |
          cd backend && npm audit --audit-level=critical || true
          cd ../frontend && npm audit --audit-level=critical || true

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest ./backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest ./frontend

      - name: Scan Trivy DevSecOps
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
          exit-code: '0'
          severity: 'CRITICAL'

      - name: Push images Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
